#ifndef ENUMS_H
#define ENUMS_H

enum TOOL {PENCIL, ERASER, CIRCLE, TRIANGLE, RECTANGLE, POLYGON, FRONT, BACK, MOUSE};

enum COLOR {RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET, BROWN, BLACK};

enum ACTION {NONE, INCREASE, DECREASE, CLEAR, UNDO};

#endif